#!/bin/bash
set -e

# 构建接口
echo Running: build-server
$(dirname $0)/build-server

# 构建rancherd
echo Running: build-rancherd
$(dirname $0)/build-rancherd
echo Running: build-agent
$(dirname $0)/build-agent
