#!/bin/bash
set -ex

echo Starting rancher server
cd $(dirname $0)/..

CMD=bin/rancher
if [ ! -x $CMD ]; then
    ./scripts/build
fi

rm -rf build/testdata
mkdir -p build/testdata
cd build/testdata
export KUBECONFIG=/root/.kube/config
export CATTLE_DEV_MODE=yes
exec ../../$CMD --add-local=true --features=multi-cluster-management=true --https-listen-port=8445
